### ISSUE TITLE
labels not showing in duckduckgo

### ISSUE THREAD

**Issue by GBT7** [EG-Freelance/stopaganda-plus#3]
I just installed this extension hoping it would work on Duckduckgo results, but it doesn't seem to. I tested it on Google results and that worked, but for duckduckgo nothing happens. I'm getting the following console messages:
```
Current page is a supported aggregator of sources; stopaganda-ddg.js:480:11
Not a Stopaganda-eligible page stopaganda-ddg.js:201:15
```

I tried on the "all" tab, the "news" tab, and the "video" tab. None worked.

**Comment by EGibbs87** [comment]
I suspect that DDG has updated their page's structure since I initially wrote the DDG implementation ~4 years ago.  I'll see what I can do to get it repaired.

**Comment by EGibbs87** [comment]
DDG has been repaired for the current release, as well as the most recent update to Reddit.  The update should already be updated to 5.2.1 in Firefox, and I expect Chrome to follow suit sometime tomorrow.

Thanks!
