### ISSUE TITLE
could use better URL matching

### ISSUE THREAD

**Issue by GBT7** [EG-Freelance/stopaganda-plus#5]
I noticed that when I tested this extension on Bloomberg, it said "High" accuracy. As I have checked the MBFC rating for Bloomberg prior, I knew that was not right, MBFC only rates them as "Mostly Factual". The reason your extension flagged it as "High" accuracy was because it was pulling up the rating for Bloomberg CityLab, not Bloomberg News, and I was not checking Bloomberg CityLab. I think the URL matching got mixed up here.

**Comment by EGibbs87** [comment]
That makes sense.  The plugin uses the base URL as the matching source.  With over 7800 sources, I never devised a fool-proof way to capture the correct matching mechanism for each and every source.  I'd guess that using base URL works for probably about 95-99% of sources, so I've stuck with that, while hardcoding exceptions for reasonably big sources.  

The example that most prominently sticks in my mind is the Borowitz Report, which uses the New Yorker as its base.  I'd certainly say that Bloomberg qualifies as a reasonable big source that needs a hardcoded exception, so I'll add that adjustment the next time I tweak the code.

Thanks for the attention you've put into auditing the data!

**Comment by EGibbs87** [comment]
Added the exception for bloomberg vs. bloomberg/citylab.  It worked in testing, so I'll just have to make sure it works when the updates are accepted.  Thanks again!

**Comment by EGibbs87** [comment]
Thanks!  Guardian/observer are now handled as well.

**Comment by EGibbs87** [comment]
Got it, thanks!  Should be updated when the next version pushes out Sunday/Monday.

**Comment by EGibbs87** [comment]
Thanks!  I'm actually going to just remove GlobalPost altogether for now.  It looks like they haven't published anything in 5 years, and something called Daily Chatter just purchased the company, so probably better to sit out until there's an actual read on it.
